### ISSUE TITLE
Does not build on OCaml 5.0: `Interpret_cmt.walk_build_dir`

### ISSUE THREAD

**Issue by lukstafi** [dariusf/ppx_debug#1]
The way I blindly fixed the build error complaining about `Load_path.init`:
```
Load_path.(init ~auto_include:(auto_include_otherlibs (fun _ -> ())) cmt.cmt_loadpath);
```

**Comment by lukstafi** [comment]
Doesn't work out-of-the-box with `opam switch 4.13.1` either:
```
File "ppx_debug_common/interpret_cmt.ml", line 135, characters 10-24:
135 |     match Types.get_desc exp_type with
                ^^^^^^^^^^^^^^
Error: Unbound value Types.get_desc
```
I'm trying `4.14.1` now.

**Comment by lukstafi** [comment]
Does build with `opam switch 4.14.1` but the demo doesn't work out-of-the-box as I mention in the other issue.

**Comment by dariusf** [comment]
Sorry for the delay, I've been swamped recently. I've fixed this using cppo, so it works on both 4.14 and 5.

**Comment by lukstafi** [comment]
Thank you! Feel free to close the issue. If you want me to close it, that'll take a while until I revisit `ppx_debug`.

**Comment by dariusf** [comment]
Alright, no worries.
